### ISSUE TITLE
B button closes overlay

### ISSUE THREAD

**Issue by SmatMan** [ppkantorski/Tetris-Overlay#16]
Hi there,

I love the idea of this overlay, and the game mechanics so far have seemed awesome and well thought out! Unfortunately, when I hit the B button to rotate a piece, it closes the overlay instead. Is there a setting I have to have enabled or something?

**Comment by ppkantorski** [comment]
sounds like a bug, i must have overlooked something when i updated libultrahand.   i'll look into it.

**Comment by ppkantorski** [comment]
Ok i've fixed the problem.

**Comment by SmatMan** [comment]
Thank you :)
